### ISSUE TITLE
jgitver is sometimes very slow due to jgit

### ISSUE THREAD

**Issue by McFoggy** [jgitver/jgitver#121]
> JGITVER USERS: see below and please provide your though via comments

From time to time the computation of project version is very long, sometimes > 30s.

By analyzing the long pauses using JFR & JMC, I found that the pause (52s in this case) was due to jgit implementation that tries to resolve the global git configuration

````
File Read
 at java.io.FileInputStream.read(byte[], int, int)
 at java.io.BufferedInputStream.read1(byte[], int, int)
 at java.io.BufferedInputStream.read(byte[], int, int)
 at sun.nio.cs.StreamDecoder.readBytes()
 at sun.nio.cs.StreamDecoder.implRead(char[], int, int)
 at sun.nio.cs.StreamDecoder.read(char[], int, int)
 at java.io.InputStreamReader.read(char[], int, int)
 at java.io.BufferedReader.fill()
 at java.io.BufferedReader.readLine(boolean)
 at java.io.BufferedReader.readLine()
 at org.eclipse.jgit.util.FS.readPipe(File, String[], String, Map)
 at org.eclipse.jgit.util.FS.discoverGitSystemConfig()
 at org.eclipse.jgit.util.FS.getGitSystemConfig()
 at org.eclipse.jgit.util.SystemReader$Default.openSystemConfig(Config, FS)
 at org.eclipse.jgit.internal.storage.file.FileRepository.<init>(BaseRepositoryBuilder)
 at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build()
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.openRepository()
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.computeVersion()
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject()
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersionObject(boolean)
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion(boolean)
 at fr.brouillard.oss.jgitver.impl.GitVersionCalculatorImpl.getVersion()
 at fr.brouillard.oss.jgitver.JGitverExtension.afterSessionStart(MavenSession)
 at org.apache.maven.DefaultMaven.doExecute(MavenExecutionRequest, MavenSession, MavenExecutionResult, DefaultRepositorySystemSession)
 at org.apache.maven.DefaultMaven.doExecute(MavenExecutionRequest)
 at org.apache.maven.DefaultMaven.execute(MavenExecutionRequest)
 at org.apache.maven.cli.MavenCli.execute(CliRequest)
 at org.apache.maven.cli.MavenCli.doMain(CliRequest)
 at org.apache.maven.cli.MavenCli.main(String[], ClassWorld)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Method, Object, Object[])
 at sun.reflect.NativeMethodAccessorImpl.invoke(Object, Object[])
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Object, Object[])
 at java.lang.reflect.Method.invoke(Object, Object[])
 at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(String[])
 at org.codehaus.plexus.classworlds.launcher.Launcher.launch(String[])
 at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(String[])
 at org.codehaus.plexus.classworlds.launcher.Launcher.main(String[])
````

There are lot of issues reporting this behavior, among others:

* https://stackoverflow.com/questions/33804097/prevent-jgit-from-reading-the-native-git-config
* https://stackoverflow.com/questions/44769837/eclipse-not-respond-when-try-to-configure-git

The first entry provide hints and direction in which to look at. 
We should evaluate if bypassing this global git configuration check is a good idea or not.

**Comment by twogee** [comment]
I see
[```
ERROR] Cannot save config file 'FileBasedConfig[/home/<ciuser>/.gitconfig]'
[04:05:42][Step 1/1] java.io.IOException: Cannot commit write to /home/<ciuser>/.gitconfig
```
so I'd like to mitigate that.

**Comment by McFoggy** [comment]
can you provide some details/context please?

**Comment by twogee** [comment]
TeamCity agents running Maven builder with jgitver extension on RHEL with SELinux that prevents writing to home directory -- is that sufficiently detailed? The pause at startup is bearable, but a stack trace in build logs is annoying.

**Comment by McFoggy** [comment]
> is that sufficiently detailed

It starts to. Sorry if I cannot imagine all the use cases the library can have...

> The pause at startup is bearable, but a stack trace in build logs is annoying.

This stack is not written by jgitver but most porbably by jgit. Run maven with -X to have the full stack trace.

> What is the point of ....

It is jgit that writes there not jgitver.

And that's the purpose of the ticket ; see if we can tell jgit not to look into/write to the git config files.

**Comment by McFoggy** [comment]
> `[filesystem "JetBrains s.r.o.|11.0.9|1383012878"]`

Looks lke it is related to IDEA or a related Jetbrains product.

**Comment by twogee** [comment]
Yes, that is from a dev machine and related to IntelliJ afaics.

**Comment by twogee** [comment]
Here's the relevant part of the stack trace from jgit showing the classes that are involved
```
[16:08:20][Step 1/1]     at org.eclipse.jgit.storage.file.FileBasedConfig.save (FileBasedConfig.java:241)
[16:08:20][Step 1/1]     at org.eclipse.jgit.util.FS$FileStoreAttributes.saveToConfig (FS.java:577)
[16:08:20][Step 1/1]     at org.eclipse.jgit.util.FS$FileStoreAttributes.lambda$0 (FS.java:357)
```

**Comment by twogee** [comment]
And [here](https://git.eclipse.org/c/jgit/jgit.git/commit/?id=838b5a84b5093c335b95a644b8888006d9e95493)'s a documentation of the feature. Looks like `XDG_CONFIG_HOME` can be used to control it?

**Comment by McFoggy** [comment]
the original issue was not related to that.
For your issue did you try to set this `XDG_CONFIG_HOME` property?

**Comment by twogee** [comment]
That's an environment variable. I believe the links above mention another variable (GIT_CONFIG_NOSYSTEM_KEY available in jgit 3.7.1+) that prevents attempts to access global configuration. Judging by the date of the commit, XDG_CONFIG_HOME is more recent (jgit 5.7+ or so), therefore I see no effect yet.

**Comment by McFoggy** [comment]
Indeed the two issues are different even if quite similar in the philosophy not depending on existing conf. Thanks for the pointers.

**Comment by twogee** [comment]
You're welcome. Here's the jgit issue describing my problem: https://bugs.eclipse.org/bugs/show_bug.cgi?id=551850
It appears to be resolved in 5.6+
