### ISSUE TITLE
If you rewrite git history, jgitver freezes at 100%

### ISSUE THREAD

**Issue by soundasleep** [jgitver/jgitver#144]
I recently migrated my repository to use `git lfs` on a number of files, and as a result I had to [rewrite the _entire_ history](https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-migrate.1.ronn#migrate-local-history) (~900 commits).

But then I found that my builds were timing out (after six hours!).

Since I use Gradle along with https://github.com/jgitver/gradle-jgitver-plugin, execution would look like it was halting silently:

```
[INFO] [org.gradle.groovy.scripts.internal.DefaultScriptCompilationHandler] Compiling build file '/home/runner/work/my/my/build.gradle' using BuildScriptTransformer.
```

With the help of debugging the [GitHub actions with SSH](https://github.com/marketplace/actions/debugging-with-ssh), I found the culprit was ultimately `jgitver`. By using `jstack`, I could see `jgitver`  was looping deep in `lookupCommits()`, trying to work out the version (for what exactly, I don't know):

```
"Daemon worker" #24 prio=5 os_prio=0 cpu=424437.50ms elapsed=440.60s tid=0x000001fbfb4559e0 nid=0x24c0 runnable  [0x000000cbabff7000]
   java.lang.Thread.State: RUNNABLE
        at java.util.stream.AbstractPipeline.wrapSink(java.base@16.0.2/AbstractPipeline.java:522)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(java.base@16.0.2/AbstractPipeline.java:474)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java.base@16.0.2/ReduceOps.java:913)
        at java.util.stream.AbstractPipeline.evaluate(java.base@16.0.2/AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(java.base@16.0.2/ReferencePipeline.java:682)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.tagsOf(GitVersionCalculator.java:388)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:342)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.lookupCommits(GitVersionCalculator.java:360)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.buildVersion(GitVersionCalculator.java:295)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.getVersionObject(GitVersionCalculator.java:166)
        at fr.brouillard.oss.jgitver.GitVersionCalculator.getVersion(GitVersionCalculator.java:224)
        at fr.brouillard.oss.gradle.plugins.JGitverPlugin$1.execute(JGitverPlugin.java:64)
        at fr.brouillard.oss.gradle.plugins.JGitverPlugin$1.execute(JGitverPlugin.java:24)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:112)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
        ... 
```

My jgitver configuration is as follows:

```gradle
jgitver {
  strategy 'PATTERN'
  versionPattern '${M}.${m}.${meta.COMMIT_DISTANCE}'     
}
```

*I found a simple workaround, however.* Create a new tag `git tag 0.xyz`, and then the version calculation is instant again.

Could it be possible for jgitver to display a log message if it's taking, say, 10 seconds+ to calculate the version? Even something that simple would have saved a few hours of my debug time.

**Comment by soloturn** [comment]
allow me to add one note completely unrelated to the issue. you might consider not using "git lfs" nowadays, but opt for partial clones like described e.g. here, and maybe add sparse checkout as well:
https://about.gitlab.com/blog/2020/03/13/partial-clone-for-massive-repositories/
```
git clone --filter=blob:none ...
```
