### ISSUE TITLE
Build fails with "Could not switch to '<git_path>/etc/"

### ISSUE THREAD

**Issue by gmerkin** [jgitver/jgitver#29]
I'm using jgitver 0.4.0, there is no "etc" directory in git installation 

INFO] Scanning for projects...
[INFO] jgitver-maven-plugin is about to change project(s) version(s)
[INFO] using jgitver configuration file: /builddata/builduser/jenkins-maven-builds/slave-molot/workspace/CTT-build-test/testingtools/ctt/.mvn/jgitver.config.xml
[ERROR] fatal: Could not switch to '/pub/tools/v2.3/git-2.6.3-1/etc/': No such file or directory

[ERROR] failure while calculating version
java.lang.IllegalStateException: failure calculating version
	at fr.brouillard.oss.jgitver.GitVersionCalculator.buildVersion(GitVersionCalculator.java:246)
	at fr.brouillard.oss.jgitver.GitVersionCalculator.getVersionObject(GitVersionCalculator.java:139)
	at fr.brouillard.oss.jgitver.GitVersionCalculator.getVersion(GitVersionCalculator.java:149)
	at fr.brouillard.oss.jgitver.JGitverVersion.<init>(JGitverVersion.java:29)
	at fr.brouillard.oss.jgitver.JGitverModelProcessor.calculateVersionIfNecessary(JGitverModelProcessor.java:126)
	at fr.brouillard.oss.jgitver.JGitverModelProcessor.provisionModel(JGitverModelProcessor.java:140)
	at fr.brouillard.oss.jgitver.JGitverModelProcessor.read(JGitverModelProcessor.java:87)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:533)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:273)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:469)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:438)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:401)
	at org.apache.maven.graph.DefaultGraphBuilder.collectProjects(DefaultGraphBuilder.java:419)
	at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor(DefaultGraphBuilder.java:410)
	at org.apache.maven.graph.DefaultGraphBuilder.build(DefaultGraphBuilder.java:83)
	at org.apache.maven.DefaultMaven.buildGraph(DefaultMaven.java:491)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:219)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Missing unknown cd874f66a8f8e0519fa1edab39139999175e0206
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:154)
	at fr.brouillard.oss.jgitver.impl.GitUtils.isDirty(GitUtils.java:51)
	at fr.brouillard.oss.jgitver.GitVersionCalculator.buildVersion(GitVersionCalculator.java:155)
	... 29 more
Caused by: org.eclipse.jgit.errors.MissingObjectException: Missing unknown cd874f66a8f8e0519fa1edab39139999175e0206
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:145)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:226)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:859)
	at org.eclipse.jgit.revwalk.RevWalk.parseTree(RevWalk.java:799)
	at org.eclipse.jgit.lib.IndexDiff.<init>(IndexDiff.java:315)
	at org.eclipse.jgit.lib.IndexDiff.<init>(IndexDiff.java:298)
	at org.eclipse.jgit.api.StatusCommand.call(StatusCommand.java:142)
	... 31 more

**Comment by McFoggy** [comment]
Can you provide more details on how your build is launched?
Jenkins? Command line?
What is the directory structure of your project? What is the working dir?

**Comment by gmerkin** [comment]
This actually occured with some sophisticated checkout setup (sparse checkout, GIT_ALTERNATE_OBJECT_DIRECTORIES env variable set). Cannot reproduce any more, the issue can be closed I think.
